spring:
  application:
    name: cln-rhy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.2.57.217:3306/institute_ms?connectionCollation=utf8mb4_general_ci&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: research
    password: Qazxsw@123
  redis:
    database: 12
    host: 10.2.56.231
    lettuce:
      pool:
        # 最大连接数据库连接数,设 0 为没有限制
        max-active: 100
        # 最大等待连接中的数量,设 0 为没有限制
        max-idle: 100
        # 最大建立连接等待时间.如果超过此时间将接到异常.设为-1表示无限制
        max-wait: 30000ms
        # 最小等待连接中的数量,设 0 为没有限制
        min-idle: 10
      # 最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100ms
    password: Qazxsw@123
    port: 6379
    # 客户端超时时间单位是毫秒
    timeout: 30000ms
server:
  port: 8888
  servlet:
    context-path: /cln
myProperty: huhuhuhu
#  huhu: huhuhuhu
my:
  value:
    pro1: pro1value
    pro2: pro2value
    file2: file:/opt/sinitek/nasdata\d?



